### ISSUE TITLE
missing dist folder in @nomiclabs/hardhat-etherscan

### ISSUE THREAD

**Issue by imajindev** [victaphu/harmony-contract-verification-tutorial#1]
somehow npm install from https://gitpkg.now.sh/victaphu/hardhat/packages/hardhat-etherscan?master
does not include the dist folder
will run into this error:
Error: Cannot find module '/node_modules/@nomiclabs/hardhat-etherscan/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by hollywoodpa** [comment]
Same for me, it looks like npm install does not include the build package
@victaphu

**Comment by imajindev** [comment]
got it working by git cloning the custom repo: https://github.com/victaphu/hardhat
then yarn install + yarn run build
copy the generated dist folder to the node_modules/@nomiclabs/hardhat-etherscan/dist
my problem now is that i cant seems to verify my upgradeable contract

**Comment by victaphu** [comment]
oh i had to remove dist to do a pr for hardhat

follow imajindev instructions (sorry for the confusion)

what is the issue with the upgradeable contract? what is the error and which library did you use?

**Comment by victaphu** [comment]
Closing as there is a workaround (see above from imajindev)

Thanks for using this, I'll clean up the env a bit so its easier to use as well
