### ISSUE TITLE
hardhat-etherscan version

### ISSUE THREAD

**Issue by dfk-earn** [victaphu/harmony-contract-verification-tutorial#2]
You mentioned using a modified version of hardhat-etherscan. I wonder do I need to use the same version to deploy and then verify contract. I deployed my contract before finding your tool, and it's likely I used a different version to deploy. 

Besides, I only see a "etherscan-verify" task for Hardhat and couldn't find the "verify" task. Is verify task replaced by the other one?

**Comment by victaphu** [comment]
Hi @dfk-earn you can now just use hardhat-etherscan plugin (https://www.npmjs.com/package/@nomiclabs/hardhat-etherscan). It has been merged into the hardhat repo. Take the latest version (3.0.3)

**Comment by dfk-earn** [comment]
Tried the 3.03 version of hardhat-etherscan plugin, worked like a charm. 

Thanks for updating the tool!
