### ISSUE TITLE
Hardhat-etherscan dist folder couldn't found

### ISSUE THREAD

**Issue by ThaiPhamCodelight** [victaphu/harmony-contract-verification-tutorial#3]
After I've installed "@nomiclabs/hardhat-etherscan": "https://gitpkg.now.sh/victaphu/hardhat/packages/hardhat-etherscan?master" 

I get Hardhat-etherscan **dist** folder couldn't found.

I've tried to build "Hardhat-etherscan" module to get dist folder by `npx tsc` then I get the following issue

![image](https://user-images.githubusercontent.com/103096799/164055365-6f244bed-40e1-4a29-8c49-7d9791313e9d.png)

**Comment by Dabsterr** [comment]
same issue here

**Comment by victaphu** [comment]
Hi all,

Please check out the latest;
Best,
Victa
